"""
questions.py — Question bank for QuizLock.
100+ questions across 5 grade bands.
Each entry: {"question": str, "choices": [str, str, str, str], "answer": str, "subject": str}
'answer' is the letter (A/B/C/D) of the correct choice.
"""

QUESTIONS: dict[str, list[dict]] = {

    # ------------------------------------------------------------------ #
    #  GRADES 1–2  (arithmetic, simple spelling, basic science)           #
    # ------------------------------------------------------------------ #
    "grade_1_2": [
        {"question": "What is 2 + 3?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 7"], "answer": "B", "subject": "Math"},
        {"question": "What is 10 - 4?",
         "choices": ["A. 5", "B. 7", "C. 6", "D. 8"], "answer": "C", "subject": "Math"},
        {"question": "What is 3 × 3?",
         "choices": ["A. 6", "B. 8", "C. 9", "D. 12"], "answer": "C", "subject": "Math"},
        {"question": "How many sides does a triangle have?",
         "choices": ["A. 2", "B. 3", "C. 4", "D. 5"], "answer": "B", "subject": "Math"},
        {"question": "Which number comes after 9?",
         "choices": ["A. 8", "B. 11", "C. 10", "D. 7"], "answer": "C", "subject": "Math"},
        {"question": "What is 4 + 4?",
         "choices": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C", "subject": "Math"},
        {"question": "What is 15 - 7?",
         "choices": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C", "subject": "Math"},
        {"question": "How many legs does a dog have?",
         "choices": ["A. 2", "B. 4", "C. 6", "D. 8"], "answer": "B", "subject": "Science"},
        {"question": "What color is the sky on a clear day?",
         "choices": ["A. Green", "B. Red", "C. Blue", "D. Yellow"], "answer": "C", "subject": "Science"},
        {"question": "Which animal says 'moo'?",
         "choices": ["A. Pig", "B. Cow", "C. Sheep", "D. Horse"], "answer": "B", "subject": "Science"},
        {"question": "How many days are in a week?",
         "choices": ["A. 5", "B. 6", "C. 7", "D. 8"], "answer": "C", "subject": "Math"},
        {"question": "What is the first letter of the alphabet?",
         "choices": ["A. B", "B. Z", "C. A", "D. M"], "answer": "C", "subject": "Language"},
        {"question": "Which shape has 4 equal sides?",
         "choices": ["A. Triangle", "B. Rectangle", "C. Circle", "D. Square"], "answer": "D", "subject": "Math"},
        {"question": "What season comes after winter?",
         "choices": ["A. Summer", "B. Fall", "C. Spring", "D. Autumn"], "answer": "C", "subject": "Science"},
        {"question": "How many fingers are on one hand?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 10"], "answer": "B", "subject": "Math"},
        {"question": "What do plants need to grow? (choose best answer)",
         "choices": ["A. Darkness only", "B. Water and sunlight", "C. Rocks", "D. Ice"], "answer": "B", "subject": "Science"},
        {"question": "What is 2 × 5?",
         "choices": ["A. 7", "B. 8", "C. 9", "D. 10"], "answer": "D", "subject": "Math"},
        {"question": "Which is bigger: 12 or 21?",
         "choices": ["A. 12", "B. 21", "C. They are equal", "D. Cannot tell"], "answer": "B", "subject": "Math"},
        {"question": "What comes after Monday?",
         "choices": ["A. Sunday", "B. Wednesday", "C. Tuesday", "D. Thursday"], "answer": "C", "subject": "Language"},
        {"question": "How many months are in a year?",
         "choices": ["A. 10", "B. 11", "C. 12", "D. 13"], "answer": "C", "subject": "Math"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 3–4  (multiplication, fractions, geography, history)        #
    # ------------------------------------------------------------------ #
    "grade_3_4": [
        {"question": "What is 7 × 8?",
         "choices": ["A. 54", "B. 56", "C. 48", "D. 63"], "answer": "B", "subject": "Math"},
        {"question": "What is 144 ÷ 12?",
         "choices": ["A. 11", "B. 13", "C. 12", "D. 14"], "answer": "C", "subject": "Math"},
        {"question": "What fraction represents one half?",
         "choices": ["A. 1/3", "B. 2/3", "C. 1/2", "D. 3/4"], "answer": "C", "subject": "Math"},
        {"question": "Which planet is closest to the Sun?",
         "choices": ["A. Venus", "B. Earth", "C. Mars", "D. Mercury"], "answer": "D", "subject": "Science"},
        {"question": "What is the capital of France?",
         "choices": ["A. Berlin", "B. Rome", "C. Madrid", "D. Paris"], "answer": "D", "subject": "Geography"},
        {"question": "How many centimeters are in a meter?",
         "choices": ["A. 10", "B. 100", "C. 1000", "D. 50"], "answer": "B", "subject": "Math"},
        {"question": "What is 9²?",
         "choices": ["A. 18", "B. 27", "C. 81", "D. 90"], "answer": "C", "subject": "Math"},
        {"question": "What is the largest continent?",
         "choices": ["A. Africa", "B. Americas", "C. Europe", "D. Asia"], "answer": "D", "subject": "Geography"},
        {"question": "How many sides does a hexagon have?",
         "choices": ["A. 5", "B. 6", "C. 7", "D. 8"], "answer": "B", "subject": "Math"},
        {"question": "What gas do plants absorb from the air?",
         "choices": ["A. Oxygen", "B. Nitrogen", "C. Carbon dioxide", "D. Hydrogen"], "answer": "C", "subject": "Science"},
        {"question": "Which ocean is the largest?",
         "choices": ["A. Atlantic", "B. Indian", "C. Arctic", "D. Pacific"], "answer": "D", "subject": "Geography"},
        {"question": "What is 25% of 100?",
         "choices": ["A. 5", "B. 20", "C. 25", "D. 75"], "answer": "C", "subject": "Math"},
        {"question": "Who was the first US President?",
         "choices": ["A. Abraham Lincoln", "B. Thomas Jefferson", "C. George Washington", "D. John Adams"],
         "answer": "C", "subject": "History"},
        {"question": "What is the boiling point of water in Celsius?",
         "choices": ["A. 0°C", "B. 50°C", "C. 100°C", "D. 212°C"], "answer": "C", "subject": "Science"},
        {"question": "What is 3/4 expressed as a decimal?",
         "choices": ["A. 0.34", "B. 0.50", "C. 0.75", "D. 1.25"], "answer": "C", "subject": "Math"},
        {"question": "What force pulls objects toward Earth?",
         "choices": ["A. Magnetism", "B. Friction", "C. Gravity", "D. Electricity"], "answer": "C", "subject": "Science"},
        {"question": "How many degrees are in a right angle?",
         "choices": ["A. 45", "B. 90", "C. 180", "D. 360"], "answer": "B", "subject": "Math"},
        {"question": "Which is the longest river in the world?",
         "choices": ["A. Amazon", "B. Mississippi", "C. Yangtze", "D. Nile"], "answer": "D", "subject": "Geography"},
        {"question": "What is 48 ÷ 6?",
         "choices": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C", "subject": "Math"},
        {"question": "What planet is known as the Red Planet?",
         "choices": ["A. Jupiter", "B. Saturn", "C. Venus", "D. Mars"], "answer": "D", "subject": "Science"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 5–6  (pre-algebra, world history, earth science)            #
    # ------------------------------------------------------------------ #
    "grade_5_6": [
        {"question": "What is the value of π (pi) rounded to 2 decimal places?",
         "choices": ["A. 3.12", "B. 3.14", "C. 3.16", "D. 3.41"], "answer": "B", "subject": "Math"},
        {"question": "What is the area of a rectangle with length 8 and width 5?",
         "choices": ["A. 13", "B. 26", "C. 40", "D. 80"], "answer": "C", "subject": "Math"},
        {"question": "Solve for x: 2x + 4 = 12",
         "choices": ["A. 2", "B. 4", "C. 6", "D. 8"], "answer": "B", "subject": "Math"},
        {"question": "What is the chemical symbol for water?",
         "choices": ["A. WA", "B. H2O", "C. HO2", "D. W"], "answer": "B", "subject": "Science"},
        {"question": "In what year did World War II end?",
         "choices": ["A. 1940", "B. 1943", "C. 1945", "D. 1948"], "answer": "C", "subject": "History"},
        {"question": "What is the largest planet in the solar system?",
         "choices": ["A. Saturn", "B. Uranus", "C. Neptune", "D. Jupiter"], "answer": "D", "subject": "Science"},
        {"question": "Which country has the largest population?",
         "choices": ["A. USA", "B. Russia", "C. India", "D. China"], "answer": "D", "subject": "Geography"},
        {"question": "What is 12³?",
         "choices": ["A. 144", "B. 1200", "C. 1728", "D. 1296"], "answer": "C", "subject": "Math"},
        {"question": "What is the main gas in Earth's atmosphere?",
         "choices": ["A. Oxygen", "B. Carbon dioxide", "C. Nitrogen", "D. Argon"], "answer": "C", "subject": "Science"},
        {"question": "What continent is Egypt in?",
         "choices": ["A. Asia", "B. Europe", "C. South America", "D. Africa"], "answer": "D", "subject": "Geography"},
        {"question": "What is the LCM of 4 and 6?",
         "choices": ["A. 8", "B. 12", "C. 18", "D. 24"], "answer": "B", "subject": "Math"},
        {"question": "Which organelle is the 'powerhouse of the cell'?",
         "choices": ["A. Nucleus", "B. Ribosome", "C. Mitochondria", "D. Vacuole"], "answer": "C", "subject": "Science"},
        {"question": "The American Civil War ended in which year?",
         "choices": ["A. 1860", "B. 1863", "C. 1865", "D. 1870"], "answer": "C", "subject": "History"},
        {"question": "What is the perimeter of a square with side 7?",
         "choices": ["A. 14", "B. 21", "C. 28", "D. 49"], "answer": "C", "subject": "Math"},
        {"question": "Which layer of Earth is outermost?",
         "choices": ["A. Mantle", "B. Core", "C. Crust", "D. Asthenosphere"], "answer": "C", "subject": "Science"},
        {"question": "How many bones are in the adult human body?",
         "choices": ["A. 186", "B. 206", "C. 216", "D. 300"], "answer": "B", "subject": "Science"},
        {"question": "What is 5/8 + 1/8?",
         "choices": ["A. 4/8", "B. 6/8 (3/4)", "C. 7/8", "D. 1"], "answer": "B", "subject": "Math"},
        {"question": "Who wrote Romeo and Juliet?",
         "choices": ["A. Charles Dickens", "B. Mark Twain", "C. William Shakespeare", "D. Jane Austen"],
         "answer": "C", "subject": "Language"},
        {"question": "What is the speed of light (approx.) in km/s?",
         "choices": ["A. 30,000", "B. 300,000", "C. 3,000,000", "D. 30,000,000"], "answer": "B", "subject": "Science"},
        {"question": "What is 20% of 250?",
         "choices": ["A. 40", "B. 50", "C. 60", "D. 25"], "answer": "B", "subject": "Math"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 7–9  (algebra, biology, world history, literature)          #
    # ------------------------------------------------------------------ #
    "grade_7_9": [
        {"question": "Simplify: (3x²)(4x³)",
         "choices": ["A. 7x⁵", "B. 12x⁵", "C. 12x⁶", "D. 7x⁶"], "answer": "B", "subject": "Math"},
        {"question": "What is the Pythagorean theorem?",
         "choices": ["A. a+b=c", "B. a²+b²=c²", "C. a²-b²=c²", "D. 2a+2b=c"], "answer": "B", "subject": "Math"},
        {"question": "What is the quadratic formula?",
         "choices": ["A. x = -b ± √(b²-4ac) / 2a",
                     "B. x = b ± √(b²-4ac) / 2a",
                     "C. x = -b ± √(b²+4ac) / 2a",
                     "D. x = -b / 2a"],
         "answer": "A", "subject": "Math"},
        {"question": "What is the process by which plants make food using sunlight?",
         "choices": ["A. Respiration", "B. Fermentation", "C. Photosynthesis", "D. Transpiration"],
         "answer": "C", "subject": "Science"},
        {"question": "In which year did the French Revolution begin?",
         "choices": ["A. 1776", "B. 1789", "C. 1804", "D. 1815"], "answer": "B", "subject": "History"},
        {"question": "What is the slope formula between two points?",
         "choices": ["A. (y2+y1)/(x2+x1)", "B. (y2-y1)/(x2-x1)", "C. (x2-x1)/(y2-y1)", "D. y=mx+b"],
         "answer": "B", "subject": "Math"},
        {"question": "DNA stands for?",
         "choices": ["A. Deoxyribonucleic Acid", "B. Dinitrogen Acid", "C. Dynamic Nucleic Array", "D. Dual Nitrogen Acid"],
         "answer": "A", "subject": "Science"},
        {"question": "What is the atomic number of Carbon?",
         "choices": ["A. 2", "B. 4", "C. 6", "D. 8"], "answer": "C", "subject": "Science"},
        {"question": "Who proposed the theory of evolution by natural selection?",
         "choices": ["A. Isaac Newton", "B. Albert Einstein", "C. Charles Darwin", "D. Gregor Mendel"],
         "answer": "C", "subject": "Science"},
        {"question": "What is the area of a circle with radius 5? (use π≈3.14)",
         "choices": ["A. 15.7", "B. 31.4", "C. 78.5", "D. 157"], "answer": "C", "subject": "Math"},
        {"question": "What is the German word for 'the'? (definite article, masculine nom.)",
         "choices": ["A. ein", "B. das", "C. der", "D. die"], "answer": "C", "subject": "Language"},
        {"question": "The Renaissance began in which country?",
         "choices": ["A. France", "B. Germany", "C. Italy", "D. England"], "answer": "C", "subject": "History"},
        {"question": "What is 2⁸?",
         "choices": ["A. 64", "B. 128", "C. 256", "D. 512"], "answer": "C", "subject": "Math"},
        {"question": "In the human body, what do red blood cells carry?",
         "choices": ["A. Nutrients", "B. Oxygen", "C. Hormones", "D. Enzymes"], "answer": "B", "subject": "Science"},
        {"question": "Factor: x² - 9",
         "choices": ["A. (x-3)²", "B. (x+9)(x-1)", "C. (x-3)(x+3)", "D. (x-9)(x+1)"], "answer": "C", "subject": "Math"},
        {"question": "Which Shakespeare play features the line 'To be or not to be'?",
         "choices": ["A. Macbeth", "B. Othello", "C. King Lear", "D. Hamlet"], "answer": "D", "subject": "Language"},
        {"question": "Newton's second law of motion states F =?",
         "choices": ["A. mv", "B. ma", "C. m/a", "D. v/t"], "answer": "B", "subject": "Science"},
        {"question": "What is the median of: 3, 7, 9, 11, 15?",
         "choices": ["A. 7", "B. 9", "C. 11", "D. 10"], "answer": "B", "subject": "Math"},
        {"question": "Which war was fought between the North and South of the United States?",
         "choices": ["A. Revolutionary War", "B. Civil War", "C. War of 1812", "D. World War I"],
         "answer": "B", "subject": "History"},
        {"question": "What is the value of sin(90°)?",
         "choices": ["A. 0", "B. 0.5", "C. √2/2", "D. 1"], "answer": "D", "subject": "Math"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 10–12  (advanced math, chemistry, literature, world events) #
    # ------------------------------------------------------------------ #
    "grade_10_plus": [
        {"question": "What is the derivative of sin(x)?",
         "choices": ["A. -sin(x)", "B. cos(x)", "C. -cos(x)", "D. tan(x)"], "answer": "B", "subject": "Math"},
        {"question": "What is the integral of 2x dx?",
         "choices": ["A. x + C", "B. 2 + C", "C. x² + C", "D. 2x² + C"], "answer": "C", "subject": "Math"},
        {"question": "What is Avogadro's number (approx.)?",
         "choices": ["A. 6.02×10²³", "B. 3.14×10²³", "C. 6.02×10²²", "D. 9.81×10²³"],
         "answer": "A", "subject": "Science"},
        {"question": "Which element has the symbol 'Au'?",
         "choices": ["A. Silver", "B. Aluminum", "C. Gold", "D. Argon"], "answer": "C", "subject": "Science"},
        {"question": "What is the value of e (Euler's number) to 3 decimal places?",
         "choices": ["A. 2.718", "B. 3.141", "C. 1.618", "D. 2.302"], "answer": "A", "subject": "Math"},
        {"question": "What does the ideal gas law state?",
         "choices": ["A. PV = nRT", "B. PV = mRT", "C. P/V = nT", "D. PV = nR/T"], "answer": "A", "subject": "Science"},
        {"question": "What is the meaning of 'hubris' in Greek tragedy?",
         "choices": ["A. Cowardice", "B. Excessive pride leading to downfall", "C. Wisdom", "D. Sacrifice"],
         "answer": "B", "subject": "Language"},
        {"question": "Who wrote '1984'?",
         "choices": ["A. Aldous Huxley", "B. Ray Bradbury", "C. George Orwell", "D. H.G. Wells"],
         "answer": "C", "subject": "Language"},
        {"question": "What is lim(x→0) sin(x)/x?",
         "choices": ["A. 0", "B. ∞", "C. 1", "D. undefined"], "answer": "C", "subject": "Math"},
        {"question": "The Treaty of Versailles ended which war?",
         "choices": ["A. World War II", "B. World War I", "C. The Cold War", "D. The Crimean War"],
         "answer": "B", "subject": "History"},
        {"question": "What is the pH of a neutral solution at 25°C?",
         "choices": ["A. 0", "B. 7", "C. 14", "D. 5"], "answer": "B", "subject": "Science"},
        {"question": "What theorem states every polynomial of degree n has exactly n complex roots?",
         "choices": ["A. Fermat's Last Theorem", "B. Fundamental Theorem of Algebra",
                     "C. Fundamental Theorem of Calculus", "D. Euclid's Theorem"],
         "answer": "B", "subject": "Math"},
        {"question": "In organic chemistry, what is a functional group with –OH?",
         "choices": ["A. Ketone", "B. Aldehyde", "C. Ester", "D. Alcohol/Hydroxyl"],
         "answer": "D", "subject": "Science"},
        {"question": "What is the determinant of [[1,2],[3,4]]?",
         "choices": ["A. 10", "B. -2", "C. 2", "D. -10"], "answer": "B", "subject": "Math"},
        {"question": "Who developed the theory of general relativity?",
         "choices": ["A. Niels Bohr", "B. Max Planck", "C. Albert Einstein", "D. Werner Heisenberg"],
         "answer": "C", "subject": "Science"},
        {"question": "What literary device uses 'the wind whispered secrets'?",
         "choices": ["A. Simile", "B. Metaphor", "C. Alliteration", "D. Personification"],
         "answer": "D", "subject": "Language"},
        {"question": "What is the standard form of an ellipse centered at origin (horizontal major axis)?",
         "choices": ["A. x²/a² + y²/b² = 1  (a>b)", "B. x²/b² + y²/a² = 1",
                     "C. x² + y² = r²", "D. y = ax² + bx + c"],
         "answer": "A", "subject": "Math"},
        {"question": "The fall of which wall symbolized the end of the Cold War?",
         "choices": ["A. Great Wall of China", "B. Hadrian's Wall", "C. Berlin Wall", "D. The Iron Curtain (physical)"],
         "answer": "C", "subject": "History"},
        {"question": "What does the Second Law of Thermodynamics describe?",
         "choices": ["A. Conservation of energy", "B. Entropy always increases in an isolated system",
                     "C. Force equals mass times acceleration", "D. Every action has an equal reaction"],
         "answer": "B", "subject": "Science"},
        {"question": "Solve: log₂(64) = ?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 8"], "answer": "C", "subject": "Math"},
    ],
}
