"""
questions.py — Question bank for QuizLock.
100+ questions across 5 grade bands.
Each entry: {"question": str, "choices": [str, str, str, str], "answer": str, "subject": str}
'answer' is the letter (A/B/C/D) of the correct choice.
"""

QUESTIONS: dict[str, list[dict]] = {

    # ------------------------------------------------------------------ #
    #  GRADES 1–2  (arithmetic, simple spelling, basic science)           #
    # ------------------------------------------------------------------ #
    "grade_1_2": [
        {"question": "What is 2 + 3?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 7"], "answer": "B", "subject": "Math"},
        {"question": "What is 10 - 4?",
         "choices": ["A. 5", "B. 7", "C. 6", "D. 8"], "answer": "C", "subject": "Math"},
        {"question": "What is 3 × 3?",
         "choices": ["A. 6", "B. 8", "C. 9", "D. 12"], "answer": "C", "subject": "Math"},
        {"question": "How many sides does a triangle have?",
         "choices": ["A. 2", "B. 3", "C. 4", "D. 5"], "answer": "B", "subject": "Math"},
        {"question": "Which number comes after 9?",
         "choices": ["A. 8", "B. 11", "C. 10", "D. 7"], "answer": "C", "subject": "Math"},
        {"question": "What is 4 + 4?",
         "choices": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C", "subject": "Math"},
        {"question": "What is 15 - 7?",
         "choices": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C", "subject": "Math"},
        {"question": "How many legs does a dog have?",
         "choices": ["A. 2", "B. 4", "C. 6", "D. 8"], "answer": "B", "subject": "Science"},
        {"question": "What color is the sky on a clear day?",
         "choices": ["A. Green", "B. Red", "C. Blue", "D. Yellow"], "answer": "C", "subject": "Science"},
        {"question": "Which animal says 'moo'?",
         "choices": ["A. Pig", "B. Cow", "C. Sheep", "D. Horse"], "answer": "B", "subject": "Science"},
        {"question": "How many days are in a week?",
         "choices": ["A. 5", "B. 6", "C. 7", "D. 8"], "answer": "C", "subject": "Math"},
        {"question": "What is the first letter of the alphabet?",
         "choices": ["A. B", "B. Z", "C. A", "D. M"], "answer": "C", "subject": "Language"},
        {"question": "Which shape has 4 equal sides?",
         "choices": ["A. Triangle", "B. Rectangle", "C. Circle", "D. Square"], "answer": "D", "subject": "Math"},
        {"question": "What season comes after winter?",
         "choices": ["A. Summer", "B. Fall", "C. Spring", "D. Autumn"], "answer": "C", "subject": "Science"},
        {"question": "How many fingers are on one hand?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 10"], "answer": "B", "subject": "Math"},
        {"question": "What do plants need to grow? (choose best answer)",
         "choices": ["A. Darkness only", "B. Water and sunlight", "C. Rocks", "D. Ice"], "answer": "B", "subject": "Science"},
        {"question": "What is 2 × 5?",
         "choices": ["A. 7", "B. 8", "C. 9", "D. 10"], "answer": "D", "subject": "Math"},
        {"question": "Which is bigger: 12 or 21?",
         "choices": ["A. 12", "B. 21", "C. They are equal", "D. Cannot tell"], "answer": "B", "subject": "Math"},
        {"question": "What comes after Monday?",
         "choices": ["A. Sunday", "B. Wednesday", "C. Tuesday", "D. Thursday"], "answer": "C", "subject": "Language"},
        {"question": "How many months are in a year?",
         "choices": ["A. 10", "B. 11", "C. 12", "D. 13"], "answer": "C", "subject": "Math"},
        {"question": "Which shape has exactly 3 corners?",
         "choices": ["A. Circle", "B. Triangle", "C. Square", "D. Oval"], "answer": "B", "subject": "IQ"},
        {"question": "Find the odd one out: Cat, Dog, Apple, Cow",
         "choices": ["A. Cat", "B. Dog", "C. Apple", "D. Cow"], "answer": "C", "subject": "IQ"},
        {"question": "What number should come next: 2, 4, 6, ?",
         "choices": ["A. 7", "B. 8", "C. 9", "D. 10"], "answer": "B", "subject": "IQ"},

        # ---- Vietnamese curriculum additions (Grades 1–2) ----
        {"question": "What is 8 + 7?",
         "choices": ["A. 13", "B. 14", "C. 15", "D. 16"], "answer": "C", "subject": "Math"},
        {"question": "What is 20 - 9?",
         "choices": ["A. 9", "B. 10", "C. 11", "D. 12"], "answer": "C", "subject": "Math"},
        {"question": "How many tens are in the number 50?",
         "choices": ["A. 3", "B. 4", "C. 5", "D. 6"], "answer": "C", "subject": "Math"},
        {"question": "What is 6 × 4?",
         "choices": ["A. 20", "B. 22", "C. 24", "D. 26"], "answer": "C", "subject": "Math"},
        {"question": "What is 30 ÷ 5?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 7"], "answer": "C", "subject": "Math"},
        {"question": "Which number is the smallest: 17, 71, 7, 70?",
         "choices": ["A. 17", "B. 71", "C. 7", "D. 70"], "answer": "C", "subject": "Math"},
        {"question": "What is 5 + 8 + 2?",
         "choices": ["A. 13", "B. 14", "C. 15", "D. 16"], "answer": "C", "subject": "Math"},
        {"question": "What is the capital city of Vietnam?",
         "choices": ["A. Ho Chi Minh City", "B. Da Nang", "C. Hanoi", "D. Hue"], "answer": "C", "subject": "Science"},
        {"question": "Which of these animals can fly?",
         "choices": ["A. Fish", "B. Dog", "C. Bird", "D. Cat"], "answer": "C", "subject": "Science"},
        {"question": "What do fish use to breathe underwater?",
         "choices": ["A. Lungs", "B. Gills", "C. Skin", "D. Mouth"], "answer": "B", "subject": "Science"},
        {"question": "The sun rises in which direction?",
         "choices": ["A. West", "B. North", "C. South", "D. East"], "answer": "D", "subject": "Science"},
        {"question": "How many seasons does northern Vietnam have?",
         "choices": ["A. 1", "B. 2", "C. 3", "D. 4"], "answer": "D", "subject": "Science"},
        {"question": "What do plants use sunlight to produce?",
         "choices": ["A. Water", "B. Soil", "C. Food", "D. Air"], "answer": "C", "subject": "Science"},
        {"question": "What is the opposite of 'day'?",
         "choices": ["A. Morning", "B. Noon", "C. Afternoon", "D. Night"], "answer": "D", "subject": "Language"},
        {"question": "Which word describes a color: big, red, run, fast?",
         "choices": ["A. Big", "B. Red", "C. Run", "D. Fast"], "answer": "B", "subject": "Language"},
        {"question": "Which sentence is correct?",
         "choices": ["A. I is a student.", "B. I are a student.", "C. I am a student.", "D. I be a student."],
         "answer": "C", "subject": "Language"},
        {"question": "What letter comes after 'M' in the English alphabet?",
         "choices": ["A. L", "B. N", "C. O", "D. P"], "answer": "B", "subject": "Language"},
        {"question": "How many vowels are in the word 'APPLE'?",
         "choices": ["A. 1", "B. 2", "C. 3", "D. 4"], "answer": "B", "subject": "Language"},
        {"question": "What comes after Tuesday?",
         "choices": ["A. Monday", "B. Thursday", "C. Wednesday", "D. Friday"], "answer": "C", "subject": "Language"},
        {"question": "Which of these is NOT a vowel?",
         "choices": ["A. A", "B. E", "C. T", "D. I"], "answer": "C", "subject": "Language"},

        # ---- Extra Vietnamese curriculum questions (Grades 1–2, Round 2) ----
        {"question": "How many ones are in the number 47?",
         "choices": ["A. 4", "B. 7", "C. 40", "D. 47"], "answer": "B", "subject": "Math"},
        {"question": "What is 9 + 6?",
         "choices": ["A. 13", "B. 14", "C. 15", "D. 16"], "answer": "C", "subject": "Math"},
        {"question": "What is 18 - 5?",
         "choices": ["A. 12", "B. 13", "C. 14", "D. 23"], "answer": "B", "subject": "Math"},
        {"question": "Which number is greater: 35 or 53?",
         "choices": ["A. 35", "B. 53", "C. They are equal", "D. Cannot tell"], "answer": "B", "subject": "Math"},
        {"question": "How many sides does a rectangle have?",
         "choices": ["A. 3", "B. 4", "C. 5", "D. 6"], "answer": "B", "subject": "Math"},
        {"question": "What is 3 × 4?",
         "choices": ["A. 7", "B. 9", "C. 12", "D. 14"], "answer": "C", "subject": "Math"},
        {"question": "What is 20 ÷ 4?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 16"], "answer": "B", "subject": "Math"},
        {"question": "Which part of the body do we use to see?",
         "choices": ["A. Ears", "B. Nose", "C. Eyes", "D. Tongue"], "answer": "C", "subject": "Science"},
        {"question": "What do we call a young dog?",
         "choices": ["A. Kitten", "B. Cub", "C. Calf", "D. Puppy"], "answer": "D", "subject": "Science"},
        {"question": "Which of these is a vegetable?",
         "choices": ["A. Apple", "B. Banana", "C. Carrot", "D. Orange"], "answer": "C", "subject": "Science"},
        {"question": "Which is the hottest season of the year?",
         "choices": ["A. Spring", "B. Summer", "C. Autumn", "D. Winter"], "answer": "B", "subject": "Science"},
        {"question": "How many senses does a human have?",
         "choices": ["A. 3", "B. 4", "C. 5", "D. 6"], "answer": "C", "subject": "Science"},
        {"question": "Which part of a plant absorbs water from the soil?",
         "choices": ["A. Leaves", "B. Stem", "C. Flowers", "D. Roots"], "answer": "D", "subject": "Science"},
        {"question": "What is the English word for the number 10?",
         "choices": ["A. Nine", "B. Ten", "C. Eleven", "D. Twelve"], "answer": "B", "subject": "Language"},
        {"question": "Which of these is a fruit?",
         "choices": ["A. Potato", "B. Carrot", "C. Orange", "D. Onion"], "answer": "C", "subject": "Language"},
        {"question": "What do we call the person who teaches students in a school?",
         "choices": ["A. Doctor", "B. Nurse", "C. Teacher", "D. Driver"], "answer": "C", "subject": "Language"},
        {"question": "Which word means the same as 'big'?",
         "choices": ["A. Small", "B. Little", "C. Tiny", "D. Large"], "answer": "D", "subject": "Language"},
        {"question": "What is the plural of 'book'?",
         "choices": ["A. Book", "B. Bookes", "C. Books", "D. Bookies"], "answer": "C", "subject": "Language"},
        {"question": "'She ___ to school every day.' Choose the correct verb.",
         "choices": ["A. Go", "B. Goes", "C. Going", "D. Gone"], "answer": "B", "subject": "Language"},
        {"question": "What color is a ripe banana?",
         "choices": ["A. Green", "B. Red", "C. Yellow", "D. Blue"], "answer": "C", "subject": "Language"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 3–4  (multiplication, fractions, geography, history)        #
    # ------------------------------------------------------------------ #
    "grade_3_4": [
        {"question": "What is 7 × 8?",
         "choices": ["A. 54", "B. 56", "C. 48", "D. 63"], "answer": "B", "subject": "Math"},
        {"question": "What is 144 ÷ 12?",
         "choices": ["A. 11", "B. 13", "C. 12", "D. 14"], "answer": "C", "subject": "Math"},
        {"question": "What fraction represents one half?",
         "choices": ["A. 1/3", "B. 2/3", "C. 1/2", "D. 3/4"], "answer": "C", "subject": "Math"},
        {"question": "Which planet is closest to the Sun?",
         "choices": ["A. Venus", "B. Earth", "C. Mars", "D. Mercury"], "answer": "D", "subject": "Science"},
        {"question": "What is the capital of France?",
         "choices": ["A. Berlin", "B. Rome", "C. Madrid", "D. Paris"], "answer": "D", "subject": "Geography"},
        {"question": "How many centimeters are in a meter?",
         "choices": ["A. 10", "B. 100", "C. 1000", "D. 50"], "answer": "B", "subject": "Math"},
        {"question": "What is 9²?",
         "choices": ["A. 18", "B. 27", "C. 81", "D. 90"], "answer": "C", "subject": "Math"},
        {"question": "What is the largest continent?",
         "choices": ["A. Africa", "B. Americas", "C. Europe", "D. Asia"], "answer": "D", "subject": "Geography"},
        {"question": "How many sides does a hexagon have?",
         "choices": ["A. 5", "B. 6", "C. 7", "D. 8"], "answer": "B", "subject": "Math"},
        {"question": "What gas do plants absorb from the air?",
         "choices": ["A. Oxygen", "B. Nitrogen", "C. Carbon dioxide", "D. Hydrogen"], "answer": "C", "subject": "Science"},
        {"question": "Which ocean is the largest?",
         "choices": ["A. Atlantic", "B. Indian", "C. Arctic", "D. Pacific"], "answer": "D", "subject": "Geography"},
        {"question": "What is 25% of 100?",
         "choices": ["A. 5", "B. 20", "C. 25", "D. 75"], "answer": "C", "subject": "Math"},
        {"question": "Who was the first US President?",
         "choices": ["A. Abraham Lincoln", "B. Thomas Jefferson", "C. George Washington", "D. John Adams"],
         "answer": "C", "subject": "History"},
        {"question": "What is the boiling point of water in Celsius?",
         "choices": ["A. 0°C", "B. 50°C", "C. 100°C", "D. 212°C"], "answer": "C", "subject": "Science"},
        {"question": "What is 3/4 expressed as a decimal?",
         "choices": ["A. 0.34", "B. 0.50", "C. 0.75", "D. 1.25"], "answer": "C", "subject": "Math"},
        {"question": "What force pulls objects toward Earth?",
         "choices": ["A. Magnetism", "B. Friction", "C. Gravity", "D. Electricity"], "answer": "C", "subject": "Science"},
        {"question": "How many degrees are in a right angle?",
         "choices": ["A. 45", "B. 90", "C. 180", "D. 360"], "answer": "B", "subject": "Math"},
        {"question": "Which is the longest river in the world?",
         "choices": ["A. Amazon", "B. Mississippi", "C. Yangtze", "D. Nile"], "answer": "D", "subject": "Geography"},
        {"question": "What is 48 ÷ 6?",
         "choices": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C", "subject": "Math"},
        {"question": "What planet is known as the Red Planet?",
         "choices": ["A. Jupiter", "B. Saturn", "C. Venus", "D. Mars"], "answer": "D", "subject": "Science"},
        {"question": "Which number does not belong: 3, 6, 9, 11?",
         "choices": ["A. 3", "B. 6", "C. 9", "D. 11"], "answer": "D", "subject": "IQ"},
        {"question": "If all bloops are razzies and all razzies are lazzies, all bloops are:",
         "choices": ["A. Not lazzies", "B. Lazzies", "C. Only razzies", "D. Animals"], "answer": "B", "subject": "IQ"},
        {"question": "What comes next: A, C, E, G, ?",
         "choices": ["A. H", "B. I", "C. J", "D. K"], "answer": "B", "subject": "IQ"},

        # ---- Vietnamese curriculum additions (Grades 3–4) ----
        {"question": "What is 234 + 158?",
         "choices": ["A. 382", "B. 392", "C. 402", "D. 412"], "answer": "B", "subject": "Math"},
        {"question": "What is 500 - 237?",
         "choices": ["A. 253", "B. 263", "C. 273", "D. 283"], "answer": "B", "subject": "Math"},
        {"question": "What is the area of a square with side 5 cm?",
         "choices": ["A. 10 cm²", "B. 20 cm²", "C. 25 cm²", "D. 30 cm²"], "answer": "C", "subject": "Math"},
        {"question": "What is the perimeter of a rectangle with length 8 cm and width 3 cm?",
         "choices": ["A. 11 cm", "B. 22 cm", "C. 24 cm", "D. 44 cm"], "answer": "B", "subject": "Math"},
        {"question": "What is 1/4 + 2/4?",
         "choices": ["A. 1/2", "B. 3/8", "C. 3/4", "D. 1"], "answer": "C", "subject": "Math"},
        {"question": "How many grams are in 1 kilogram?",
         "choices": ["A. 100", "B. 500", "C. 1000", "D. 10000"], "answer": "C", "subject": "Math"},
        {"question": "Round 847 to the nearest hundred.",
         "choices": ["A. 900", "B. 850", "C. 800", "D. 840"], "answer": "C", "subject": "Math"},
        {"question": "What is 56 ÷ 8?",
         "choices": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "B", "subject": "Math"},
        {"question": "Which of these is a source of light?",
         "choices": ["A. The Moon", "B. A rock", "C. The Sun", "D. A mirror"], "answer": "C", "subject": "Science"},
        {"question": "What gas do humans need to breathe to survive?",
         "choices": ["A. Carbon dioxide", "B. Nitrogen", "C. Oxygen", "D. Hydrogen"], "answer": "C", "subject": "Science"},
        {"question": "What type of animal is a dolphin?",
         "choices": ["A. Fish", "B. Reptile", "C. Bird", "D. Mammal"], "answer": "D", "subject": "Science"},
        {"question": "What organ pumps blood throughout the body?",
         "choices": ["A. Lung", "B. Brain", "C. Kidney", "D. Heart"], "answer": "D", "subject": "Science"},
        {"question": "What happens to water when heated to 100°C?",
         "choices": ["A. It freezes", "B. It turns to steam", "C. It disappears", "D. It turns solid"],
         "answer": "B", "subject": "Science"},
        {"question": "What is the plural of 'child'?",
         "choices": ["A. Childs", "B. Childes", "C. Children", "D. Childrens"], "answer": "C", "subject": "Language"},
        {"question": "What is the past tense of 'eat'?",
         "choices": ["A. Eated", "B. Eaten", "C. Ate", "D. Eat"], "answer": "C", "subject": "Language"},
        {"question": "Which word is a verb: beautiful, table, jump, apple?",
         "choices": ["A. Beautiful", "B. Table", "C. Jump", "D. Apple"], "answer": "C", "subject": "Language"},
        {"question": "What punctuation mark ends a question?",
         "choices": ["A. Period (.)", "B. Comma (,)", "C. Question mark (?)", "D. Exclamation mark (!)"],
         "answer": "C", "subject": "Language"},
        {"question": "What is the opposite of 'tall'?",
         "choices": ["A. Big", "B. Long", "C. Short", "D. Fat"], "answer": "C", "subject": "Language"},
        {"question": "'There ___ many students in the class.' Choose the correct word.",
         "choices": ["A. Is", "B. Are", "C. Was", "D. Am"], "answer": "B", "subject": "Language"},
        {"question": "Which article is correct? '___ apple a day keeps the doctor away.'",
         "choices": ["A. A", "B. An", "C. The", "D. No article"], "answer": "B", "subject": "Language"},

        # ---- Extra Vietnamese curriculum questions (Grades 3–4, Round 2) ----
        {"question": "What is 456 × 3?",
         "choices": ["A. 1268", "B. 1358", "C. 1368", "D. 1468"], "answer": "C", "subject": "Math"},
        {"question": "What is 1200 ÷ 4?",
         "choices": ["A. 200", "B. 250", "C. 300", "D. 400"], "answer": "C", "subject": "Math"},
        {"question": "What time is it when the hour hand points to 3 and the minute hand points to 12?",
         "choices": ["A. 12:03", "B. 3:00", "C. 3:12", "D. 12:15"], "answer": "B", "subject": "Math"},
        {"question": "How many milliliters are in 1 liter?",
         "choices": ["A. 10", "B. 100", "C. 1000", "D. 10000"], "answer": "C", "subject": "Math"},
        {"question": "What is the perimeter of an equilateral triangle with side length 6 cm?",
         "choices": ["A. 12 cm", "B. 15 cm", "C. 18 cm", "D. 36 cm"], "answer": "C", "subject": "Math"},
        {"question": "What is 2/3 of 12?",
         "choices": ["A. 4", "B. 6", "C. 8", "D. 9"], "answer": "C", "subject": "Math"},
        {"question": "Round 1,456 to the nearest thousand.",
         "choices": ["A. 1000", "B. 1500", "C. 2000", "D. 1400"], "answer": "A", "subject": "Math"},
        {"question": "How many hours are in 2 days?",
         "choices": ["A. 24", "B. 36", "C. 48", "D. 60"], "answer": "C", "subject": "Math"},
        {"question": "What organ do we use to breathe?",
         "choices": ["A. Heart", "B. Liver", "C. Kidney", "D. Lungs"], "answer": "D", "subject": "Science"},
        {"question": "What is the role of the stomach in digestion?",
         "choices": ["A. Pumping blood", "B. Filtering waste", "C. Breaking down food", "D. Absorbing oxygen"],
         "answer": "C", "subject": "Science"},
        {"question": "What do herbivores eat?",
         "choices": ["A. Only other animals", "B. Plants", "C. Both animals and plants", "D. Insects only"],
         "answer": "B", "subject": "Science"},
        {"question": "In what state of matter does water fall as snow?",
         "choices": ["A. Liquid", "B. Gas", "C. Solid", "D. Plasma"], "answer": "C", "subject": "Science"},
        {"question": "What is the water cycle process where water rises from rivers and lakes into the air?",
         "choices": ["A. Rainfall", "B. Condensation", "C. Evaporation", "D. Freezing"], "answer": "C", "subject": "Science"},
        {"question": "What is the past tense of 'go'?",
         "choices": ["A. Goed", "B. Gone", "C. Went", "D. Going"], "answer": "C", "subject": "Language"},
        {"question": "Which word is an adjective: run, beautiful, slowly, table?",
         "choices": ["A. Run", "B. Beautiful", "C. Slowly", "D. Table"], "answer": "B", "subject": "Language"},
        {"question": "'She ___ playing football now.' Choose the correct verb.",
         "choices": ["A. Are", "B. Am", "C. Is", "D. Were"], "answer": "C", "subject": "Language"},
        {"question": "What is the opposite of 'cold'?",
         "choices": ["A. Cool", "B. Warm", "C. Hot", "D. Chilly"], "answer": "C", "subject": "Language"},
        {"question": "What is the English word for the shape with no corners or sides?",
         "choices": ["A. Square", "B. Triangle", "C. Rectangle", "D. Circle"], "answer": "D", "subject": "Language"},
        {"question": "How do you spell the number that comes after 'nineteen'?",
         "choices": ["A. Twentee", "B. Twenty", "C. Twente", "D. Twenti"], "answer": "B", "subject": "Language"},
        {"question": "'How ___ students are in the class?' Choose the correct word.",
         "choices": ["A. Much", "B. Many", "C. Old", "D. Long"], "answer": "B", "subject": "Language"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 5–6  (pre-algebra, world history, earth science)            #
    # ------------------------------------------------------------------ #
    "grade_5_6": [
        {"question": "What is the value of π (pi) rounded to 2 decimal places?",
         "choices": ["A. 3.12", "B. 3.14", "C. 3.16", "D. 3.41"], "answer": "B", "subject": "Math"},
        {"question": "What is the area of a rectangle with length 8 and width 5?",
         "choices": ["A. 13", "B. 26", "C. 40", "D. 80"], "answer": "C", "subject": "Math"},
        {"question": "Solve for x: 2x + 4 = 12",
         "choices": ["A. 2", "B. 4", "C. 6", "D. 8"], "answer": "B", "subject": "Math"},
        {"question": "What is the chemical symbol for water?",
         "choices": ["A. WA", "B. H2O", "C. HO2", "D. W"], "answer": "B", "subject": "Science"},
        {"question": "In what year did World War II end?",
         "choices": ["A. 1940", "B. 1943", "C. 1945", "D. 1948"], "answer": "C", "subject": "History"},
        {"question": "What is the largest planet in the solar system?",
         "choices": ["A. Saturn", "B. Uranus", "C. Neptune", "D. Jupiter"], "answer": "D", "subject": "Science"},
        {"question": "Which country has the largest population?",
         "choices": ["A. USA", "B. Russia", "C. India", "D. China"], "answer": "D", "subject": "Geography"},
        {"question": "What is 12³?",
         "choices": ["A. 144", "B. 1200", "C. 1728", "D. 1296"], "answer": "C", "subject": "Math"},
        {"question": "What is the main gas in Earth's atmosphere?",
         "choices": ["A. Oxygen", "B. Carbon dioxide", "C. Nitrogen", "D. Argon"], "answer": "C", "subject": "Science"},
        {"question": "What continent is Egypt in?",
         "choices": ["A. Asia", "B. Europe", "C. South America", "D. Africa"], "answer": "D", "subject": "Geography"},
        {"question": "What is the LCM of 4 and 6?",
         "choices": ["A. 8", "B. 12", "C. 18", "D. 24"], "answer": "B", "subject": "Math"},
        {"question": "Which organelle is the 'powerhouse of the cell'?",
         "choices": ["A. Nucleus", "B. Ribosome", "C. Mitochondria", "D. Vacuole"], "answer": "C", "subject": "Science"},
        {"question": "The American Civil War ended in which year?",
         "choices": ["A. 1860", "B. 1863", "C. 1865", "D. 1870"], "answer": "C", "subject": "History"},
        {"question": "What is the perimeter of a square with side 7?",
         "choices": ["A. 14", "B. 21", "C. 28", "D. 49"], "answer": "C", "subject": "Math"},
        {"question": "Which layer of Earth is outermost?",
         "choices": ["A. Mantle", "B. Core", "C. Crust", "D. Asthenosphere"], "answer": "C", "subject": "Science"},
        {"question": "How many bones are in the adult human body?",
         "choices": ["A. 186", "B. 206", "C. 216", "D. 300"], "answer": "B", "subject": "Science"},
        {"question": "What is 5/8 + 1/8?",
         "choices": ["A. 4/8", "B. 6/8 (3/4)", "C. 7/8", "D. 1"], "answer": "B", "subject": "Math"},
        {"question": "Who wrote Romeo and Juliet?",
         "choices": ["A. Charles Dickens", "B. Mark Twain", "C. William Shakespeare", "D. Jane Austen"],
         "answer": "C", "subject": "Language"},
        {"question": "What is the speed of light (approx.) in km/s?",
         "choices": ["A. 30,000", "B. 300,000", "C. 3,000,000", "D. 30,000,000"], "answer": "B", "subject": "Science"},
        {"question": "What is 20% of 250?",
         "choices": ["A. 40", "B. 50", "C. 60", "D. 25"], "answer": "B", "subject": "Math"},
        {"question": "Which number continues the pattern: 1, 1, 2, 3, 5, 8, ?",
         "choices": ["A. 10", "B. 11", "C. 13", "D. 15"], "answer": "C", "subject": "IQ"},
        {"question": "A clock shows 3:15. What is the angle between hour and minute hands (smallest)?",
         "choices": ["A. 0 degrees", "B. 7.5 degrees", "C. 15 degrees", "D. 30 degrees"], "answer": "B", "subject": "IQ"},
        {"question": "Find the odd one out: Square, Triangle, Circle, Cube",
         "choices": ["A. Square", "B. Triangle", "C. Circle", "D. Cube"], "answer": "D", "subject": "IQ"},

        # ---- Vietnamese curriculum additions (Grades 5–6) ----
        {"question": "What is 15% of 80?",
         "choices": ["A. 8", "B. 10", "C. 12", "D. 15"], "answer": "C", "subject": "Math"},
        {"question": "What is the volume of a cube with side length 4 cm?",
         "choices": ["A. 16 cm³", "B. 48 cm³", "C. 64 cm³", "D. 96 cm³"], "answer": "C", "subject": "Math"},
        {"question": "Solve for x: 5x - 10 = 15",
         "choices": ["A. x = 3", "B. x = 5", "C. x = 7", "D. x = 25"], "answer": "B", "subject": "Math"},
        {"question": "What is the area of a triangle with base 12 cm and height 5 cm?",
         "choices": ["A. 17 cm²", "B. 30 cm²", "C. 60 cm²", "D. 120 cm²"], "answer": "B", "subject": "Math"},
        {"question": "What is the greatest common divisor (GCD) of 24 and 36?",
         "choices": ["A. 4", "B. 6", "C. 9", "D. 12"], "answer": "D", "subject": "Math"},
        {"question": "Express 0.6 as a fraction in its simplest form.",
         "choices": ["A. 6/10", "B. 3/5", "C. 2/3", "D. 6/5"], "answer": "B", "subject": "Math"},
        {"question": "What is -5 + 8?",
         "choices": ["A. -13", "B. -3", "C. 3", "D. 13"], "answer": "C", "subject": "Math"},
        {"question": "What is the ratio of 15 to 25 in its simplest form?",
         "choices": ["A. 1:2", "B. 3:5", "C. 5:3", "D. 15:25"], "answer": "B", "subject": "Math"},
        {"question": "What is the formula for speed?",
         "choices": ["A. v = d × t", "B. v = t / d", "C. v = d / t", "D. v = d + t"], "answer": "C", "subject": "Science"},
        {"question": "Which state of matter has a definite volume but no definite shape?",
         "choices": ["A. Solid", "B. Liquid", "C. Gas", "D. Plasma"], "answer": "B", "subject": "Science"},
        {"question": "What is the SI unit of electric current?",
         "choices": ["A. Volt", "B. Watt", "C. Ohm", "D. Ampere"], "answer": "D", "subject": "Science"},
        {"question": "The process of a liquid turning into gas is called?",
         "choices": ["A. Condensation", "B. Freezing", "C. Evaporation", "D. Sublimation"], "answer": "C", "subject": "Science"},
        {"question": "What is the chemical symbol for the element Iron?",
         "choices": ["A. Ir", "B. Io", "C. Fe", "D. In"], "answer": "C", "subject": "Science"},
        {"question": "How many planets are in our solar system?",
         "choices": ["A. 7", "B. 8", "C. 9", "D. 10"], "answer": "B", "subject": "Science"},
        {"question": "What is the most abundant element in the Earth's crust?",
         "choices": ["A. Silicon", "B. Hydrogen", "C. Iron", "D. Oxygen"], "answer": "D", "subject": "Science"},
        {"question": "Which planet is known for its prominent ring system?",
         "choices": ["A. Jupiter", "B. Uranus", "C. Saturn", "D. Neptune"], "answer": "C", "subject": "Science"},
        {"question": "What is the past participle of the verb 'write'?",
         "choices": ["A. Wrote", "B. Written", "C. Writed", "D. Write"], "answer": "B", "subject": "Language"},
        {"question": "Which word functions as an adverb: quick, quicker, quickly, quickness?",
         "choices": ["A. Quick", "B. Quicker", "C. Quickly", "D. Quickness"], "answer": "C", "subject": "Language"},
        {"question": "'She has lived in Hanoi ___ 2010.' Choose the correct preposition.",
         "choices": ["A. For", "B. Since", "C. From", "D. In"], "answer": "B", "subject": "Language"},
        {"question": "What is a synonym for 'happy'?",
         "choices": ["A. Sad", "B. Angry", "C. Joyful", "D. Tired"], "answer": "C", "subject": "Language"},
        {"question": "Identify the adjective in: 'The quick brown fox jumps over the lazy dog.'",
         "choices": ["A. Fox", "B. Jumps", "C. Quick", "D. Over"], "answer": "C", "subject": "Language"},
        {"question": "Which sentence is grammatically correct?",
         "choices": ["A. He don't know the answer.",
                     "B. He doesn't knows the answer.",
                     "C. He doesn't know the answer.",
                     "D. He isn't know the answer."],
         "answer": "C", "subject": "Language"},
        {"question": "What does the word 'frequently' mean?",
         "choices": ["A. Never", "B. Rarely", "C. Once", "D. Often"], "answer": "D", "subject": "Language"},

        # ---- Extra Vietnamese curriculum questions (Grades 5–6, Round 2) ----
        {"question": "What is 2.5 × 4?",
         "choices": ["A. 8", "B. 9", "C. 10", "D. 12"], "answer": "C", "subject": "Math"},
        {"question": "What is 3/4 of 80?",
         "choices": ["A. 40", "B. 60", "C. 75", "D. 20"], "answer": "B", "subject": "Math"},
        {"question": "Convert 3/4 to a percentage.",
         "choices": ["A. 34%", "B. 43%", "C. 75%", "D. 80%"], "answer": "C", "subject": "Math"},
        {"question": "What is the circumference of a circle with radius 5 cm? (use π ≈ 3.14)",
         "choices": ["A. 15.7 cm", "B. 25 cm", "C. 31.4 cm", "D. 78.5 cm"], "answer": "C", "subject": "Math"},
        {"question": "What is the surface area of a cube with side length 3 cm?",
         "choices": ["A. 9 cm²", "B. 27 cm²", "C. 54 cm²", "D. 108 cm²"], "answer": "C", "subject": "Math"},
        {"question": "What is 125% of 40?",
         "choices": ["A. 45", "B. 48", "C. 50", "D. 55"], "answer": "C", "subject": "Math"},
        {"question": "A train travels at 60 km/h for 2.5 hours. How far does it travel?",
         "choices": ["A. 120 km", "B. 135 km", "C. 150 km", "D. 180 km"], "answer": "C", "subject": "Math"},
        {"question": "What is the LCM (Least Common Multiple) of 8 and 12?",
         "choices": ["A. 4", "B. 8", "C. 16", "D. 24"], "answer": "D", "subject": "Math"},
        {"question": "What is the SI unit of force?",
         "choices": ["A. Joule", "B. Pascal", "C. Newton", "D. Watt"], "answer": "C", "subject": "Science"},
        {"question": "What type of energy is stored in food?",
         "choices": ["A. Kinetic energy", "B. Chemical energy", "C. Thermal energy", "D. Nuclear energy"],
         "answer": "B", "subject": "Science"},
        {"question": "What type of rock is formed when lava cools and solidifies?",
         "choices": ["A. Sedimentary", "B. Metamorphic", "C. Igneous", "D. Limestone"], "answer": "C", "subject": "Science"},
        {"question": "What is the SI unit of temperature?",
         "choices": ["A. Celsius", "B. Fahrenheit", "C. Kelvin", "D. Rankine"], "answer": "C", "subject": "Science"},
        {"question": "When carbon burns completely in oxygen, what gas is produced?",
         "choices": ["A. Carbon monoxide", "B. Carbon dioxide", "C. Oxygen", "D. Nitrogen"], "answer": "B", "subject": "Science"},
        {"question": "What is the name of the force that opposes motion between two surfaces?",
         "choices": ["A. Gravity", "B. Magnetism", "C. Friction", "D. Tension"], "answer": "C", "subject": "Science"},
        {"question": "Which layer of the atmosphere contains the ozone layer?",
         "choices": ["A. Troposphere", "B. Stratosphere", "C. Mesosphere", "D. Thermosphere"], "answer": "B", "subject": "Science"},
        {"question": "What do we call animals that eat both plants and other animals?",
         "choices": ["A. Herbivores", "B. Carnivores", "C. Omnivores", "D. Decomposers"], "answer": "C", "subject": "Science"},
        {"question": "'By the time she arrived, the movie ___ already started.' Choose the correct verb.",
         "choices": ["A. Has", "B. Have", "C. Had", "D. Would have"], "answer": "C", "subject": "Language"},
        {"question": "What is the meaning of the idiom 'break a leg'?",
         "choices": ["A. Get injured", "B. Dance well", "C. Run fast", "D. Good luck"], "answer": "D", "subject": "Language"},
        {"question": "Choose the correct question tag: 'She is a doctor, ___?'",
         "choices": ["A. Is she?", "B. Isn't she?", "C. Wasn't she?", "D. Doesn't she?"], "answer": "B", "subject": "Language"},
        {"question": "What is the correct reported speech for: 'I am going home,' he said.",
         "choices": ["A. He said that he is going home.",
                     "B. He said that he was going home.",
                     "C. He said that I was going home.",
                     "D. He said that he will go home."],
         "answer": "B", "subject": "Language"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 7–9  (algebra, biology, world history, literature)          #
    # ------------------------------------------------------------------ #
    "grade_7_9": [
        {"question": "Simplify: (3x²)(4x³)",
         "choices": ["A. 7x⁵", "B. 12x⁵", "C. 12x⁶", "D. 7x⁶"], "answer": "B", "subject": "Math"},
        {"question": "What is the Pythagorean theorem?",
         "choices": ["A. a+b=c", "B. a²+b²=c²", "C. a²-b²=c²", "D. 2a+2b=c"], "answer": "B", "subject": "Math"},
        {"question": "What is the quadratic formula?",
         "choices": ["A. x = -b ± √(b²-4ac) / 2a",
                     "B. x = b ± √(b²-4ac) / 2a",
                     "C. x = -b ± √(b²+4ac) / 2a",
                     "D. x = -b / 2a"],
         "answer": "A", "subject": "Math"},
        {"question": "What is the process by which plants make food using sunlight?",
         "choices": ["A. Respiration", "B. Fermentation", "C. Photosynthesis", "D. Transpiration"],
         "answer": "C", "subject": "Science"},
        {"question": "In which year did the French Revolution begin?",
         "choices": ["A. 1776", "B. 1789", "C. 1804", "D. 1815"], "answer": "B", "subject": "History"},
        {"question": "What is the slope formula between two points?",
         "choices": ["A. (y2+y1)/(x2+x1)", "B. (y2-y1)/(x2-x1)", "C. (x2-x1)/(y2-y1)", "D. y=mx+b"],
         "answer": "B", "subject": "Math"},
        {"question": "DNA stands for?",
         "choices": ["A. Deoxyribonucleic Acid", "B. Dinitrogen Acid", "C. Dynamic Nucleic Array", "D. Dual Nitrogen Acid"],
         "answer": "A", "subject": "Science"},
        {"question": "What is the atomic number of Carbon?",
         "choices": ["A. 2", "B. 4", "C. 6", "D. 8"], "answer": "C", "subject": "Science"},
        {"question": "Who proposed the theory of evolution by natural selection?",
         "choices": ["A. Isaac Newton", "B. Albert Einstein", "C. Charles Darwin", "D. Gregor Mendel"],
         "answer": "C", "subject": "Science"},
        {"question": "What is the area of a circle with radius 5? (use π≈3.14)",
         "choices": ["A. 15.7", "B. 31.4", "C. 78.5", "D. 157"], "answer": "C", "subject": "Math"},
        {"question": "What is the German word for 'the'? (definite article, masculine nom.)",
         "choices": ["A. ein", "B. das", "C. der", "D. die"], "answer": "C", "subject": "Language"},
        {"question": "The Renaissance began in which country?",
         "choices": ["A. France", "B. Germany", "C. Italy", "D. England"], "answer": "C", "subject": "History"},
        {"question": "What is 2⁸?",
         "choices": ["A. 64", "B. 128", "C. 256", "D. 512"], "answer": "C", "subject": "Math"},
        {"question": "In the human body, what do red blood cells carry?",
         "choices": ["A. Nutrients", "B. Oxygen", "C. Hormones", "D. Enzymes"], "answer": "B", "subject": "Science"},
        {"question": "Factor: x² - 9",
         "choices": ["A. (x-3)²", "B. (x+9)(x-1)", "C. (x-3)(x+3)", "D. (x-9)(x+1)"], "answer": "C", "subject": "Math"},
        {"question": "Which Shakespeare play features the line 'To be or not to be'?",
         "choices": ["A. Macbeth", "B. Othello", "C. King Lear", "D. Hamlet"], "answer": "D", "subject": "Language"},
        {"question": "Newton's second law of motion states F =?",
         "choices": ["A. mv", "B. ma", "C. m/a", "D. v/t"], "answer": "B", "subject": "Science"},
        {"question": "What is the median of: 3, 7, 9, 11, 15?",
         "choices": ["A. 7", "B. 9", "C. 11", "D. 10"], "answer": "B", "subject": "Math"},
        {"question": "Which war was fought between the North and South of the United States?",
         "choices": ["A. Revolutionary War", "B. Civil War", "C. War of 1812", "D. World War I"],
         "answer": "B", "subject": "History"},
        {"question": "What is the value of sin(90°)?",
         "choices": ["A. 0", "B. 0.5", "C. √2/2", "D. 1"], "answer": "D", "subject": "Math"},
        {"question": "If BOOK is coded as CPPL, TREE is coded as USFF. STAR is coded as:",
         "choices": ["A. TUBS", "B. TUBR", "C. TUAS", "D. RUAS"], "answer": "A", "subject": "IQ"},
        {"question": "Which is the next number: 2, 6, 12, 20, 30, ?",
         "choices": ["A. 36", "B. 40", "C. 42", "D. 44"], "answer": "C", "subject": "IQ"},
        {"question": "A is taller than B, B is taller than C. Who is shortest?",
         "choices": ["A. A", "B. B", "C. C", "D. Cannot tell"], "answer": "C", "subject": "IQ"},

        # ---- Vietnamese curriculum additions (Grades 7–9) ----
        {"question": "What is the sum of interior angles of any quadrilateral?",
         "choices": ["A. 180°", "B. 270°", "C. 360°", "D. 720°"], "answer": "C", "subject": "Math"},
        {"question": "Solve for x: 3x + 2 = 2x - 5",
         "choices": ["A. x = 7", "B. x = -7", "C. x = 3", "D. x = -3"], "answer": "B", "subject": "Math"},
        {"question": "What is √144?",
         "choices": ["A. 10", "B. 11", "C. 12", "D. 14"], "answer": "C", "subject": "Math"},
        {"question": "What is the probability of getting heads when flipping a fair coin?",
         "choices": ["A. 1/4", "B. 1/3", "C. 1/2", "D. 2/3"], "answer": "C", "subject": "Math"},
        {"question": "What is the mean (average) of: 4, 8, 12, 16, 20?",
         "choices": ["A. 10", "B. 12", "C. 14", "D. 16"], "answer": "B", "subject": "Math"},
        {"question": "Does a triangle with sides 5, 12, and 13 form a right triangle?",
         "choices": ["A. No, it is not a right triangle",
                     "B. Yes, because 5² + 12² = 13²",
                     "C. Yes, but only because one angle is acute",
                     "D. Cannot be determined"],
         "answer": "B", "subject": "Math"},
        {"question": "Simplify: 2³ × 2⁴",
         "choices": ["A. 2⁷ (128)", "B. 4⁷", "C. 2¹²", "D. 2⁶ (64)"], "answer": "A", "subject": "Math"},
        {"question": "What is the formula for kinetic energy?",
         "choices": ["A. KE = mv", "B. KE = mv²", "C. KE = ½mv²", "D. KE = mgh"], "answer": "C", "subject": "Science"},
        {"question": "What is the SI unit of electrical resistance?",
         "choices": ["A. Volt", "B. Ampere", "C. Watt", "D. Ohm"], "answer": "D", "subject": "Science"},
        {"question": "Ohm's Law states: V = ?",
         "choices": ["A. V = I / R", "B. V = I × R", "C. V = R / I", "D. V = I + R"], "answer": "B", "subject": "Science"},
        {"question": "What type of wave is sound?",
         "choices": ["A. Transverse wave", "B. Longitudinal wave", "C. Electromagnetic wave", "D. Surface wave"],
         "answer": "B", "subject": "Science"},
        {"question": "What is the chemical formula for table salt?",
         "choices": ["A. NaOH", "B. NaCl", "C. KCl", "D. CaCl₂"], "answer": "B", "subject": "Science"},
        {"question": "What is the atomic number of Sodium (Na)?",
         "choices": ["A. 9", "B. 10", "C. 11", "D. 12"], "answer": "C", "subject": "Science"},
        {"question": "An atom that has gained extra electrons becomes a:",
         "choices": ["A. Positive ion (cation)", "B. Isotope", "C. Neutron", "D. Negative ion (anion)"],
         "answer": "D", "subject": "Science"},
        {"question": "How many chambers does the human heart have?",
         "choices": ["A. 2", "B. 3", "C. 4", "D. 5"], "answer": "C", "subject": "Science"},
        {"question": "What is the largest organ in the human body?",
         "choices": ["A. Liver", "B. Brain", "C. Lungs", "D. Skin"], "answer": "D", "subject": "Science"},
        {"question": "What is the primary function of the cell nucleus?",
         "choices": ["A. Produces energy for the cell",
                     "B. Controls cell activities and contains DNA",
                     "C. Stores water and nutrients",
                     "D. Destroys old proteins"],
         "answer": "B", "subject": "Science"},
        {"question": "'If it ___ tomorrow, we will cancel the trip.' Choose the correct verb form.",
         "choices": ["A. Rain", "B. Rains", "C. Will rain", "D. Rained"], "answer": "B", "subject": "Language"},
        {"question": "What does the prefix 'un-' mean in the word 'unhappy'?",
         "choices": ["A. Very", "B. Again", "C. Not", "D. Before"], "answer": "C", "subject": "Language"},
        {"question": "Which word is a conjunction: quickly, beautiful, although, toward?",
         "choices": ["A. Quickly", "B. Beautiful", "C. Although", "D. Toward"], "answer": "C", "subject": "Language"},
        {"question": "What is a 'metaphor' in English?",
         "choices": ["A. A comparison using 'like' or 'as'",
                     "B. A direct comparison stating one thing is another",
                     "C. Giving human qualities to objects",
                     "D. Exaggeration for emphasis"],
         "answer": "B", "subject": "Language"},
        {"question": "What is the comparative form of the adjective 'far'?",
         "choices": ["A. More far", "B. Farrest", "C. Farther / Further", "D. Farer"], "answer": "C", "subject": "Language"},
        {"question": "Choose the correct passive voice: 'They built this bridge in 1990.'",
         "choices": ["A. This bridge was build in 1990.",
                     "B. This bridge was built in 1990.",
                     "C. This bridge is built in 1990.",
                     "D. This bridge has been build in 1990."],
         "answer": "B", "subject": "Language"},

        # ---- Extra Vietnamese curriculum questions (Grades 7–9, Round 2) ----
        {"question": "What is the value of 3² + 4²?",
         "choices": ["A. 7", "B. 14", "C. 25", "D. 49"], "answer": "C", "subject": "Math"},
        {"question": "Solve: x² - 5x + 6 = 0",
         "choices": ["A. x = 1 or x = 6", "B. x = 2 or x = 3", "C. x = -2 or x = -3", "D. x = -1 or x = 6"],
         "answer": "B", "subject": "Math"},
        {"question": "What is the formula for the volume of a cylinder with radius r and height h?",
         "choices": ["A. V = πr²h", "B. V = 2πrh", "C. V = πr²/h", "D. V = 4/3πr³"], "answer": "A", "subject": "Math"},
        {"question": "What is the slope of a line passing through the points (0, 3) and (2, 7)?",
         "choices": ["A. 1", "B. 2", "C. 3", "D. 4"], "answer": "B", "subject": "Math"},
        {"question": "The ratio of boys to girls is 3:2 and there are 25 students total. How many boys are there?",
         "choices": ["A. 10", "B. 12", "C. 15", "D. 18"], "answer": "C", "subject": "Math"},
        {"question": "What is the exterior angle of a regular hexagon?",
         "choices": ["A. 30°", "B. 45°", "C. 60°", "D. 120°"], "answer": "C", "subject": "Math"},
        {"question": "What is 3.6 × 10⁴ written in standard (expanded) form?",
         "choices": ["A. 360", "B. 3,600", "C. 36,000", "D. 360,000"], "answer": "C", "subject": "Math"},
        {"question": "What is the SI unit of pressure?",
         "choices": ["A. Newton", "B. Joule", "C. Pascal", "D. Watt"], "answer": "C", "subject": "Science"},
        {"question": "What does a concave lens do to parallel light rays?",
         "choices": ["A. Converges them to a focal point", "B. Diverges them",
                     "C. Absorbs them", "D. Reflects them back"], "answer": "B", "subject": "Science"},
        {"question": "If v is the speed of a wave, f is its frequency, and λ is its wavelength, which formula is correct?",
         "choices": ["A. v = f + λ", "B. v = f / λ", "C. v = f × λ", "D. v = λ / f"], "answer": "C", "subject": "Science"},
        {"question": "What is the valency (combining power) of Oxygen?",
         "choices": ["A. 1", "B. 2", "C. 3", "D. 4"], "answer": "B", "subject": "Science"},
        {"question": "What gas is released when an acid reacts with a metal carbonate?",
         "choices": ["A. Hydrogen", "B. Oxygen", "C. Carbon dioxide", "D. Nitrogen"], "answer": "C", "subject": "Science"},
        {"question": "What is the chemical formula for sulfuric acid?",
         "choices": ["A. H₂S", "B. SO₃", "C. H₂SO₃", "D. H₂SO₄"], "answer": "D", "subject": "Science"},
        {"question": "What type of chemical bond is formed by sharing electrons between atoms?",
         "choices": ["A. Ionic bond", "B. Metallic bond", "C. Covalent bond", "D. Hydrogen bond"],
         "answer": "C", "subject": "Science"},
        {"question": "What is the process by which cells break down glucose to release energy?",
         "choices": ["A. Photosynthesis", "B. Digestion", "C. Cellular respiration", "D. Transpiration"],
         "answer": "C", "subject": "Science"},
        {"question": "During which phase of cell division do chromosomes align along the cell's equator?",
         "choices": ["A. Prophase", "B. Metaphase", "C. Anaphase", "D. Telophase"], "answer": "B", "subject": "Science"},
        {"question": "'If I ___ you, I would apologize immediately.' Choose the correct verb form.",
         "choices": ["A. Am", "B. Is", "C. Was", "D. Were"], "answer": "D", "subject": "Language"},
        {"question": "What is the superlative form of 'good'?",
         "choices": ["A. Better", "B. Gooder", "C. Best", "D. Most good"], "answer": "C", "subject": "Language"},
        {"question": "What does 'benevolent' mean?",
         "choices": ["A. Selfish and greedy", "B. Angry and hostile", "C. Generous and kind", "D. Careless and reckless"],
         "answer": "C", "subject": "Language"},
        {"question": "What is the passive voice of: 'The teacher corrects the homework every day.'?",
         "choices": ["A. The homework corrects the teacher.",
                     "B. The homework is corrected by the teacher.",
                     "C. The homework was corrected by the teacher.",
                     "D. The homework has been corrected by the teacher."],
         "answer": "B", "subject": "Language"},
    ],

    # ------------------------------------------------------------------ #
    #  GRADES 10–12  (advanced math, chemistry, literature, world events) #
    # ------------------------------------------------------------------ #
    "grade_10_plus": [
        {"question": "What is the derivative of sin(x)?",
         "choices": ["A. -sin(x)", "B. cos(x)", "C. -cos(x)", "D. tan(x)"], "answer": "B", "subject": "Math"},
        {"question": "What is the integral of 2x dx?",
         "choices": ["A. x + C", "B. 2 + C", "C. x² + C", "D. 2x² + C"], "answer": "C", "subject": "Math"},
        {"question": "What is Avogadro's number (approx.)?",
         "choices": ["A. 6.02×10²³", "B. 3.14×10²³", "C. 6.02×10²²", "D. 9.81×10²³"],
         "answer": "A", "subject": "Science"},
        {"question": "Which element has the symbol 'Au'?",
         "choices": ["A. Silver", "B. Aluminum", "C. Gold", "D. Argon"], "answer": "C", "subject": "Science"},
        {"question": "What is the value of e (Euler's number) to 3 decimal places?",
         "choices": ["A. 2.718", "B. 3.141", "C. 1.618", "D. 2.302"], "answer": "A", "subject": "Math"},
        {"question": "What does the ideal gas law state?",
         "choices": ["A. PV = nRT", "B. PV = mRT", "C. P/V = nT", "D. PV = nR/T"], "answer": "A", "subject": "Science"},
        {"question": "What is the meaning of 'hubris' in Greek tragedy?",
         "choices": ["A. Cowardice", "B. Excessive pride leading to downfall", "C. Wisdom", "D. Sacrifice"],
         "answer": "B", "subject": "Language"},
        {"question": "Who wrote '1984'?",
         "choices": ["A. Aldous Huxley", "B. Ray Bradbury", "C. George Orwell", "D. H.G. Wells"],
         "answer": "C", "subject": "Language"},
        {"question": "What is lim(x→0) sin(x)/x?",
         "choices": ["A. 0", "B. ∞", "C. 1", "D. undefined"], "answer": "C", "subject": "Math"},
        {"question": "The Treaty of Versailles ended which war?",
         "choices": ["A. World War II", "B. World War I", "C. The Cold War", "D. The Crimean War"],
         "answer": "B", "subject": "History"},
        {"question": "What is the pH of a neutral solution at 25°C?",
         "choices": ["A. 0", "B. 7", "C. 14", "D. 5"], "answer": "B", "subject": "Science"},
        {"question": "What theorem states every polynomial of degree n has exactly n complex roots?",
         "choices": ["A. Fermat's Last Theorem", "B. Fundamental Theorem of Algebra",
                     "C. Fundamental Theorem of Calculus", "D. Euclid's Theorem"],
         "answer": "B", "subject": "Math"},
        {"question": "In organic chemistry, what is a functional group with –OH?",
         "choices": ["A. Ketone", "B. Aldehyde", "C. Ester", "D. Alcohol/Hydroxyl"],
         "answer": "D", "subject": "Science"},
        {"question": "What is the determinant of [[1,2],[3,4]]?",
         "choices": ["A. 10", "B. -2", "C. 2", "D. -10"], "answer": "B", "subject": "Math"},
        {"question": "Who developed the theory of general relativity?",
         "choices": ["A. Niels Bohr", "B. Max Planck", "C. Albert Einstein", "D. Werner Heisenberg"],
         "answer": "C", "subject": "Science"},
        {"question": "What literary device uses 'the wind whispered secrets'?",
         "choices": ["A. Simile", "B. Metaphor", "C. Alliteration", "D. Personification"],
         "answer": "D", "subject": "Language"},
        {"question": "What is the standard form of an ellipse centered at origin (horizontal major axis)?",
         "choices": ["A. x²/a² + y²/b² = 1  (a>b)", "B. x²/b² + y²/a² = 1",
                     "C. x² + y² = r²", "D. y = ax² + bx + c"],
         "answer": "A", "subject": "Math"},
        {"question": "The fall of which wall symbolized the end of the Cold War?",
         "choices": ["A. Great Wall of China", "B. Hadrian's Wall", "C. Berlin Wall", "D. The Iron Curtain (physical)"],
         "answer": "C", "subject": "History"},
        {"question": "What does the Second Law of Thermodynamics describe?",
         "choices": ["A. Conservation of energy", "B. Entropy always increases in an isolated system",
                     "C. Force equals mass times acceleration", "D. Every action has an equal reaction"],
         "answer": "B", "subject": "Science"},
        {"question": "Solve: log₂(64) = ?",
         "choices": ["A. 4", "B. 5", "C. 6", "D. 8"], "answer": "C", "subject": "Math"},
        {"question": "Which number should replace ?: 3, 9, 27, 81, ?",
         "choices": ["A. 162", "B. 243", "C. 324", "D. 729"], "answer": "B", "subject": "IQ"},
        {"question": "If some artists are teachers and all teachers are readers, which is always true?",
         "choices": ["A. All artists are readers", "B. Some readers are artists", "C. No artists are readers", "D. All readers are teachers"], "answer": "B", "subject": "IQ"},
        {"question": "Find the odd one out: 8, 27, 64, 100, 125",
         "choices": ["A. 8", "B. 27", "C. 100", "D. 125"], "answer": "C", "subject": "IQ"},

        # ---- Vietnamese curriculum additions (Grades 10–12) ----
        {"question": "What is the derivative of f(x) = x³ - 2x² + 5?",
         "choices": ["A. 3x² + 5", "B. x² - 2x", "C. 3x² - 4x", "D. 3x² - 4x + 5"], "answer": "C", "subject": "Math"},
        {"question": "What is log₁₀(1000)?",
         "choices": ["A. 2", "B. 3", "C. 4", "D. 10"], "answer": "B", "subject": "Math"},
        {"question": "Evaluate: sin²(45°) + cos²(45°)",
         "choices": ["A. 0", "B. √2", "C. 1", "D. 2"], "answer": "C", "subject": "Math"},
        {"question": "What is the sum of the arithmetic series 1 + 2 + 3 + ... + 100?",
         "choices": ["A. 4950", "B. 5000", "C. 5050", "D. 5100"], "answer": "C", "subject": "Math"},
        {"question": "If f(x) = 3x + 2, what is the inverse function f⁻¹(x)?",
         "choices": ["A. 3 / (x + 2)", "B. (x + 2) / 3", "C. (x - 2) / 3", "D. 3x - 2"], "answer": "C", "subject": "Math"},
        {"question": "The equation x² + y² = 25 represents a circle. What is its radius?",
         "choices": ["A. √5", "B. 5", "C. 10", "D. 25"], "answer": "B", "subject": "Math"},
        {"question": "What is the integral of cos(x) dx?",
         "choices": ["A. -cos(x) + C", "B. sin(x) + C", "C. -sin(x) + C", "D. tan(x) + C"], "answer": "B", "subject": "Math"},
        {"question": "Expand: (a + b)²",
         "choices": ["A. a² + b²", "B. a² + ab + b²", "C. a² + 2ab + b²", "D. 2a² + 2b²"], "answer": "C", "subject": "Math"},
        {"question": "What is the SI unit of power?",
         "choices": ["A. Joule", "B. Newton", "C. Watt", "D. Pascal"], "answer": "C", "subject": "Science"},
        {"question": "What is the approximate speed of sound in air at room temperature?",
         "choices": ["A. 300 m/s", "B. 340 m/s", "C. 3000 m/s", "D. 1500 m/s"], "answer": "B", "subject": "Science"},
        {"question": "What does Einstein's equation E = mc² describe?",
         "choices": ["A. Kinetic energy of a moving object",
                     "B. Mass-energy equivalence",
                     "C. Ohm's law in circuits",
                     "D. Newton's second law"],
         "answer": "B", "subject": "Science"},
        {"question": "What is the formula for gravitational potential energy?",
         "choices": ["A. PE = ½mv²", "B. PE = mgh", "C. PE = Fd", "D. PE = mc²"], "answer": "B", "subject": "Science"},
        {"question": "What is the molecular formula of glucose?",
         "choices": ["A. C₆H₁₂O₆", "B. C₆H₆", "C. CH₂O", "D. C₁₂H₂₂O₁₁"], "answer": "A", "subject": "Science"},
        {"question": "A solution with a pH less than 7 is classified as:",
         "choices": ["A. Neutral", "B. Basic", "C. Acidic", "D. Alkaline"], "answer": "C", "subject": "Science"},
        {"question": "In a redox reaction, oxidation is defined as:",
         "choices": ["A. Gain of electrons", "B. Loss of protons", "C. Loss of electrons", "D. Gain of protons"],
         "answer": "C", "subject": "Science"},
        {"question": "What is Hess's Law in chemistry related to?",
         "choices": ["A. Entropy change in a reaction",
                     "B. Enthalpy of reaction",
                     "C. Rate of a chemical reaction",
                     "D. Equilibrium constant"],
         "answer": "B", "subject": "Science"},
        {"question": "What is the basic unit of heredity?",
         "choices": ["A. Cell", "B. Chromosome", "C. Gene", "D. Nucleus"], "answer": "C", "subject": "Science"},
        {"question": "A gene that is always expressed when present is called:",
         "choices": ["A. Recessive", "B. Dominant", "C. Codominant", "D. Heterozygous"], "answer": "B", "subject": "Science"},
        {"question": "In English, the term 'gerund' refers to:",
         "choices": ["A. A verb in the past tense",
                     "B. A verb form used as a noun (ending in -ing)",
                     "C. An adjective modifying a verb",
                     "D. A word connecting two clauses"],
         "answer": "B", "subject": "Language"},
        {"question": "What is a 'paradox' in literature?",
         "choices": ["A. A comparison using 'like' or 'as'",
                     "B. A seemingly contradictory statement that reveals a truth",
                     "C. Giving human qualities to non-human things",
                     "D. Exaggeration for dramatic effect"],
         "answer": "B", "subject": "Language"},
        {"question": "Identify the correct sentence using the subjunctive mood.",
         "choices": ["A. It is important that he is present.",
                     "B. It is important that he be present.",
                     "C. It is important that he was present.",
                     "D. It is important that he being present."],
         "answer": "B", "subject": "Language"},
        {"question": "What does the word 'ephemeral' mean?",
         "choices": ["A. Eternal and everlasting", "B. Vast and wide", "C. Extremely bright", "D. Lasting for a very short time"],
         "answer": "D", "subject": "Language"},
        {"question": "'No sooner ___ he arrived than she left.' Choose the correct auxiliary verb.",
         "choices": ["A. Did", "B. Has", "C. Had", "D. Was"], "answer": "C", "subject": "Language"},
        {"question": "What literary device is used in: 'The world is a stage'?",
         "choices": ["A. Simile", "B. Personification", "C. Metaphor", "D. Hyperbole"], "answer": "C", "subject": "Language"},

        # ---- Extra Vietnamese curriculum questions (Grades 10–12, Round 2) ----
        {"question": "What is the derivative of tan(x)?",
         "choices": ["A. -tan(x)", "B. sec²(x)", "C. cot(x)", "D. cos²(x)"], "answer": "B", "subject": "Math"},
        {"question": "What is the sum of the infinite geometric series: 1 + 1/2 + 1/4 + 1/8 + ...?",
         "choices": ["A. 1", "B. 1.5", "C. 2", "D. It diverges"], "answer": "C", "subject": "Math"},
        {"question": "What is the value of i² (where i is the imaginary unit √-1)?",
         "choices": ["A. 1", "B. -1", "C. i", "D. -i"], "answer": "B", "subject": "Math"},
        {"question": "What is the cross product of two parallel (non-zero) vectors?",
         "choices": ["A. A unit vector", "B. Zero vector", "C. A vector of length 1", "D. The dot product"],
         "answer": "B", "subject": "Math"},
        {"question": "What is the area under the curve y = x² from x = 0 to x = 3?",
         "choices": ["A. 3", "B. 6", "C. 9", "D. 27"], "answer": "C", "subject": "Math"},
        {"question": "In how many ways can 5 distinct objects be arranged in a row?",
         "choices": ["A. 25", "B. 60", "C. 120", "D. 720"], "answer": "C", "subject": "Math"},
        {"question": "What is the domain of f(x) = √(x - 3)?",
         "choices": ["A. x > 0", "B. x > 3", "C. x ≥ 3", "D. All real numbers"], "answer": "C", "subject": "Math"},
        {"question": "What is cos(π)?",
         "choices": ["A. 0", "B. 1", "C. -1", "D. √2/2"], "answer": "C", "subject": "Math"},
        {"question": "What is the formula for the electric field strength E at distance r from a point charge Q? (k = Coulomb's constant)",
         "choices": ["A. E = kQ/r", "B. E = kQ/r²", "C. E = kQ²/r", "D. E = kQr"], "answer": "B", "subject": "Science"},
        {"question": "Which type of electromagnetic radiation has the highest frequency?",
         "choices": ["A. Radio waves", "B. Visible light", "C. X-rays", "D. Gamma rays"], "answer": "D", "subject": "Science"},
        {"question": "What does the Heisenberg Uncertainty Principle state?",
         "choices": ["A. Energy is conserved in all reactions",
                     "B. Entropy always increases in isolated systems",
                     "C. The position and momentum of a particle cannot both be precisely known simultaneously",
                     "D. Mass and energy are equivalent"],
         "answer": "C", "subject": "Science"},
        {"question": "What is the formula for the period T of a simple pendulum of length L? (g = gravitational acceleration)",
         "choices": ["A. T = 2π√(L/g)", "B. T = 2πL/g", "C. T = 2π√(g/L)", "D. T = √(L/g)"],
         "answer": "A", "subject": "Science"},
        {"question": "What are the products of a neutralisation reaction between an acid and a base?",
         "choices": ["A. Salt and hydrogen", "B. Salt and water", "C. Oxide and water", "D. Gas and oxide"],
         "answer": "B", "subject": "Science"},
        {"question": "What is the general molecular formula for an alkane?",
         "choices": ["A. CₙHₙ", "B. CₙH₂ₙ", "C. CₙH₂ₙ₊₂", "D. CₙH₂ₙ₋₂"], "answer": "C", "subject": "Science"},
        {"question": "What is electronegativity?",
         "choices": ["A. The number of electrons in an atom",
                     "B. The ability of an atom to attract electrons toward itself in a bond",
                     "C. The energy released when an electron is added to an atom",
                     "D. The charge carried by an ion"],
         "answer": "B", "subject": "Science"},
        {"question": "What is the central dogma of molecular biology?",
         "choices": ["A. Protein → RNA → DNA", "B. RNA → DNA → Protein",
                     "C. DNA → RNA → Protein", "D. DNA → Protein → RNA"],
         "answer": "C", "subject": "Science"},
        {"question": "What is the Hardy-Weinberg principle used to describe?",
         "choices": ["A. Mutation rates in a population",
                     "B. Allele frequencies in a non-evolving population",
                     "C. Species biodiversity in ecosystems",
                     "D. The rate of cell division"],
         "answer": "B", "subject": "Science"},
        {"question": "What is the difference between 'affect' and 'effect'?",
         "choices": ["A. They are synonyms with no difference",
                     "B. 'Affect' is usually a verb; 'effect' is usually a noun",
                     "C. 'Effect' is a verb; 'affect' is a noun",
                     "D. Both are used only as nouns"],
         "answer": "B", "subject": "Language"},
        {"question": "What is the term for words that sound the same but have different meanings and spellings (e.g., 'there' and 'their')?",
         "choices": ["A. Homograph", "B. Synonym", "C. Antonym", "D. Homophone"], "answer": "D", "subject": "Language"},
        {"question": "What is an 'oxymoron' in literature?",
         "choices": ["A. An obvious, overstated truth",
                     "B. A figure of speech combining two contradictory terms (e.g., 'living dead')",
                     "C. An extreme exaggeration for emphasis",
                     "D. A question asked for effect rather than an answer"],
         "answer": "B", "subject": "Language"},
    ],
}
